### ISSUE TITLE
MS Teams notifications are currently broken with new message format

### ISSUE THREAD

**Issue by wargamez** [kubereboot/kured#1024]
Microsoft are urging users to convert to a / generate a  new url for webhook by December. This new format which adds a new path to existing webhook urls seems not to be supported by shoutrrr https://github.com/containrrr/shoutrrr/issues/446. Any plans to change this library which seems like it hasn't gotten any commits in over a year? (To be clear, I am not talking about MS workflows, just new webhook urls) 

old:
https://<organization>.webhook.office.com/webhookb2/<group>@<tenant>/IncomingWebhook/<altId>/<groupOwner>

new:
https://<organization>.webhook.office.com/webhookb2/<group>@<tenant>/IncomingWebhook/<altId>/<groupOwner>/<newSegment>

/E

**Comment by dv0gt** [comment]
Any news here?? There is one week left only!

**Comment by evrardjp** [comment]
I don't have an environment for testing. 
Did you try, by any chance, what's written in https://github.com/containrrr/shoutrrr/issues/446#issuecomment-2563269374 ?

**Comment by heathharrelson** [comment]
A colleague and I just spent an annoying amount of time figuring this out, so I wanted to document our solution here. After [updating your Teams webhook connector URL to the new format](https://learn.microsoft.com/en-us/microsoftteams/m365-custom-connectors#update-connectors-url), you can configure kured to notify the channel using [shoutrrr's generic webhook with the `json` template](https://containrrr.dev/shoutrrr/v0.8/services/generic/#json_template).

Copy the updated Teams connector URL and set kured's `--notify-url` (`configuration.notifyUrl` in the Helm chart) to:

```
generic://<organization>.webhook.office.com/webhookb2/...?template=json&messagekey=text
```

Note that `https://` has been replaced by `generic://` and query parameters have been added to the URL. This will get things working until shoutrrr supports workflows or you find some other solution.

**Comment by wargamez** [comment]
Thanks @heathharrelson, that did the trick!

**Comment by jorgephiguera** [comment]
If you are using external-secrets operator and extraEnvVars in the helm charts, this makes the conversion. 


```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kured-settings
spec:
 ...
  target:
    template:
      data:
        KURED_NOTIFY_URL: '{{ list .msteamsWebhookUrl "template=json&messagekey=text" | join "?" | replace "https://" "generic://" }}'
```
But i am not sure if the variable is correct. I am doing some tests
https://github.com/kubereboot/kured/pull/464

**Comment by jorgelon** [comment]
If you are using external-secrets operator and extraEnvVars in the helm charts, this makes the conversion.

But i am not sure if the variable is correct. I am doing some tests

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kured-settings
spec:
 ...
  target:
    template:
      data:
        KURED_NOTIFY_URL: '{{ list .msteamsWebhookUrl "template=json&messagekey=text" | join "?" | replace "https://" "generic://" }}'
```
