### ISSUE TITLE
overrive options with envvars

### ISSUE THREAD

**Issue by ludook** [kubereboot/kured#1142]
Hello,

is it possible to override options with envvars ?

for example, notifyUrl can contain some sensitive information.
So it will be more secure if with could inject this config from envars (issued from a kube secret for example)

in the associated helm chart, it referes to such a feature : 
https://github.com/kubereboot/charts/blob/main/charts/kured/values.yaml
```
extraEnvVars:
#  - name: slackHookUrl
#    valueFrom:
#      secretKeyRef:
#        name: secret_name
#        key: secret_key
```
but it seems not working with notifyUrl for example

maybe I missed some documentation or maybe it is not possible to override all parameters with envvars ?

thank you for your great job :-)

**Comment by evrardjp** [comment]
Env vars should be okay. Can you check if the env var name is matching the expectations?

Which env var are you using ? How do you pass it? What's the value ?

**Comment by ludook** [comment]
what do you mean by "matching the expectations" ? where I can find these expectations ? 
how do you tranform --notify-url , in the corresponding envvars to be defined ? 

I guess `notifyUrl` ? if I believe the comment in the helm chart values file I found here : 
https://github.com/kubereboot/charts/blob/main/charts/kured/values.yaml ?

what I tried :

I would like to set --notify-url param by envvar (issued from a kube secret)
like that in the kured daemonset: 
```
spec:
    spec:
      containers:
      - args:
        - --ds-name=kubereboot-kured
        - --ds-namespace=kured
        command:
        - /usr/bin/kured
        env:
        - name: notifyUrl
          valueFrom:
            secretKeyRef:
              key: notifyUrl
              name: kured
```
with a secret defined as : 
```
apiVersion: v1
kind: Secret
metadata:
  name: kured
  namespace: kured
type: Opaque
stringData:
  notifyUrl: slack://****/***/***
```

instead of passing options as described in the kured doc : 
```
spec:
    spec:
      containers:
      - args:
        - --ds-name=kubereboot-kured
        - --ds-namespace=kured
        - --notify-url=slack://****/***/***
        command:
        - /usr/bin/kured
```
which is working as expected : slack notifications are sent 👍 

when I set notifyUrl as envar on daemonset : 
`notifyUrl` is set as envvar in each kured pod, but no notification is sent anymore
envvars is correctly set in all pods: checked with a pod exec `env` cmd
I checked connexions and url of course, with a curl cmd
and there is no error in pods logs : envar seems not be taken into account

I tried these kind of syntax for envvar name : 
notifyUrl
NOTIFY_URL
NOTIFYURL
KURED_NOTIFYURL
but nothing seems to work

I missed something ?
