### ISSUE TITLE
improve security of sentinel mechanism

### ISSUE THREAD

**Issue by rptaylor** [kubereboot/kured#526]
The default sentinel behaviour is to check for the existence of a file on the host. This is done using a `test -f` command executed on the host with nsenter:
https://github.com/weaveworks/kured/blob/main/cmd/kured/main.go#L661

I would propose refactoring this to achieve the same thing in a different way, using a (read-only) hostPath to check for existence of a file on the host, while keeping the non-default option to run an arbitrary sentinel command in the host namespace unchanged. In conjunction with #416  this would allow kured to be non-privileged.  This could mostly be handled by the Helm chart, mounting a configurable directory on the host (the sentinel file itself could not be mounted as a file-type hostPath because it would normally not exist).

```
volumes: 
  - name: sentinel
    hostPath:
      path: /somewhere_configurable
      type: Directory
```      
      
```  
volumeMounts:
  - name: sentinel
    mountPath: /somewhere_arbitrary
    readOnly: true
```

A rebootSentinel option already exists in the helm chart and kured CLI.
Looks like these helm [path helpers](https://helm.sh/docs/chart_template_guide/accessing_files/#path-helpers) would be perfect to split up the given rebootSentinel path; `Dir` could be used to get the hostPath directory to mount and `Base` could be passed to the kured executable, to find the file name inside the arbitrary directory in the pod.
