### ISSUE TITLE
Existing Helm chart deployments are broken

### ISSUE THREAD

**Issue by dan-leanix** [kubereboot/kured#654]
Due to this change https://github.com/kubereboot/kured/pull/645 I am assuming that all existing Helm chart deployments are broken.

We received this morning the following error in Terraform:

```
Error: looks like "https://weaveworks.github.io/kured" is not a valid chart repository or cannot be reached: failed to fetch https://weaveworks.github.io/kured/index.yaml : 404 Not Found
```

We are using the following Helm chart https://artifacthub.io/packages/helm/kured/kured/3.0.0.

Thanks,
Daniel

**Comment by dan-leanix** [comment]
We could change the repository config to `https://kubereboot.github.io/kured/index.yaml` but the URLs in the `index.yaml` are still referencing the old repository with the wrong redirect.

```
  kured:
  - apiVersion: v1
    appVersion: 1.10.2
    created: "2022-08-20T09:11:27.828539459Z"
    ...
    name: kured
    sources:
    - https://github.com/weaveworks/kured
    urls:
    - https://weaveworks.github.io/kured/kured-3.0.1.tgz
    version: 3.0.1
```
