### ISSUE TITLE
Env in in command?

### ISSUE THREAD

**Issue by harrytang** [kubereboot/kured#733]
Hi, is it possible to use the env in the `command`, for example `XOXB` like this?
```yaml
env:
  - name: XOXB
    valueFrom:
      secretKeyRef:
        name: kured-env
        key: XOXB
command:
  - /usr/bin/kured
  - --notify-url="slack://xoxb:$XOXB@notifications?botname=Kured"
```            
Seems it does not work for me.
