### ISSUE TITLE
Deamonset has no port configuration

### ISSUE THREAD

**Issue by PaulusTM** [kubereboot/kured#741]
In order to let a PodMonitor scrape the metrics endpoint the DaemonSet container spec needs an ports spec.

Would you accept an pr for this?

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kured
spec:
  template:
    spec:
      containers:
        - name: kured
          ports:
            - containerPort: 8080
              name: metrics
```
