### ISSUE TITLE
Sentinel Command not working

### ISSUE THREAD

**Issue by schmittvictor** [kubereboot/kured#954]
The Sentinel Command is not working on kubernetes using helm chart deployment:

In my values.yaml:

```
  rebootCommand: /bin/systemctl reboot
  rebootSentinel: /var/run/reboot-required
  rebootSentinelCommand: sh -c "! needs-restarting --reboothint"
```

In the daemonset, reboot-sentinel-command is missing:

```
    spec:
      containers:
        - args:
            - '--ds-name=kured'
            - '--ds-namespace=kube-system'
            - '--metrics-port=8080'
            - '--period=0h0m30s'
            - '--reboot-sentinel=/sentinel/reboot-required'
            - '--reboot-command=/bin/systemctl reboot'
            - '--log-format=text'
            - '--concurrency=1'
          command:
            - /usr/bin/kured
```
