### ISSUE TITLE
Allow creation of exclusion windows

### ISSUE THREAD

**Issue by rbjorklin** [kubereboot/kured#963]
I dug around in the issues and found that scheduling was requested in #48 and implemented in #66. This is a great start but ideally `kured` can also support exclusion windows. Something along these lines:

```yaml
exclusions:
  - name: Black Week / Black Friday
    start: "2024-11-25T00:00:00Z"
    end: "2024-11-30T23:59:59Z"
  - name: Holidays
    start: "2024-12-23T16:00:00Z"
    end: "2025-01-02T10:00:00Z"
```

The idea being that during the exclusion windows the schedule is not respected and no nodes are being restarted. The motivation here is that I don't want to get paged during my time off or intentionally cause disruptions when the system is running at full tilt.
