### ISSUE TITLE
No prometheus metrics from kured on a control plane node

### ISSUE THREAD

**Issue by amrap030** [kubereboot/kured#998]
Hello, I am running kured with Helm in the version 5.5.0 and kured v1.16.0 in my Kubernete Cluster with v1.31.1. I want to use prometheus and grafana to monitor kured, so I enabled the service monitor via the Helm values with the following configuration:

```yaml
metrics:
    create: true
    namespace: ""
    labels:
      release: kube-prometheus-stack
    interval: 60s
    scrapeTimeout: ""
```

I have 3 nodes in my cluster, 1 control plane and 2 worker nodes. For some reason, prometheus only catches the metrics of the pods on the worker nodes and not of the pod on the control plane, see image below.

![image](https://github.com/user-attachments/assets/369fa147-e654-4ac7-a588-b4edbf3e73d9)

If I set `hostNetwork: true` in the Helm values, it works fine, see image below.

![image](https://github.com/user-attachments/assets/c3cc169b-c7a6-432d-b100-f218eaf4d89f)

However, I don't want to set `hostNetwork: true`. Do you have an idea what might be the problem here?
